(function () {
    const birthdayCss = document.createElement('link');birthdayCss.rel='stylesheet';birthdayCss.href='styles/birthday-section.css?v=20260814-4';document.head.appendChild(birthdayCss);
    const main=document.querySelector('main');if(main&&!document.getElementById('birthday')){const section=document.createElement('section');section.className='container birthday-section';section.id='birthday';section.innerHTML=`<div class="birthday-wrap"><div class="birthday-hero"><div class="birthday-copy"><p class="birthday-kicker">Muhammadali • Birthday System</p><h2>Next <span>Level Up.</span></h2><p>Личный birthday-раздел. Полная Birthday System открывается только 15 августа по времени Ташкента.</p><div class="birthday-status"><span class="birthday-status-dot"></span><b id="birthdayStatusText">Загрузка Birthday System...</b></div></div><div class="birthday-logo-card"><div class="birthday-emblem" id="birthdayEmblem"><span class="cake">🎂</span><span class="level-badge">14</span></div></div></div><div class="birthday-countdown-card"><h3 id="birthdayCountdownTitle">До следующего дня рождения</h3><p id="birthdayCountdownSubtitle">15 августа • 00:00 • Ташкент</p><div class="birthday-countdown"><div class="birthday-time-box"><strong id="birthdayDays">--</strong><span>дней</span></div><div class="birthday-time-box"><strong id="birthdayHours">--</strong><span>часов</span></div><div class="birthday-time-box"><strong id="birthdayMinutes">--</strong><span>минут</span></div><div class="birthday-time-box"><strong id="birthdaySeconds">--</strong><span>секунд</span></div></div><div class="birthday-actions"><a class="birthday-link" href="birthday/?v=20260814-4">Открыть Birthday System <span>→</span></a></div><div id="birthdayCelebration" class="birthday-celebration"><b>LEVEL 14 🚀</b><p>Birthday mode активен сегодня.</p></div></div><div class="birthday-mini-grid"><div class="birthday-mini-card"><b>🎂 Birthday</b><span>15 августа.</span></div><div class="birthday-mini-card"><b>⚡ Annual lock</b><span>Полная система доступна только один день в году.</span></div><div class="birthday-mini-card"><b>🥚 Easter eggs</b><span>Некоторые элементы сайта скрывают секреты.</span></div></div><div class="birthday-countdown-card" style="margin-top:1.5rem"><p class="birthday-kicker">LEVEL HISTORY</p><h3>Твоя линия уровней</h3><div class="birthday-mini-grid"><div class="birthday-mini-card"><b>2012 • LEVEL 0</b><span>Начало.</span></div><div class="birthday-mini-card"><b>2026 • LEVEL 14</b><span>Текущий уровень.</span></div><div class="birthday-mini-card"><b>2027 • LEVEL 15</b><span>Заблокирован 🔒</span></div></div></div></div>`;main.appendChild(section)}
    const controls=document.querySelector('.controls');if(controls&&!controls.querySelector('[data-id="birthday"]')){const c=document.createElement('div');c.className='control';c.dataset.id='birthday';c.title='Birthday';c.innerHTML='<i class="fas fa-birthday-cake"></i>';controls.appendChild(c)}
    [...document.querySelectorAll('.control')].forEach(button=>button.addEventListener('click',function(){document.querySelector('.active-btn')?.classList.remove('active-btn');this.classList.add('active-btn');document.querySelector('.active')?.classList.remove('active');document.getElementById(button.dataset.id)?.classList.add('active')}));
    document.querySelector('.theme-btn')?.addEventListener('click',()=>document.body.classList.toggle('light-mode'));
})();

document.querySelector('.contact-form')?.addEventListener('submit',async function(event){event.preventDefault();const name=this.querySelector('input[name="name"]').value,email=this.querySelector('input[name="email"]').value,subject=this.querySelector('input[name="subject"]').value,message=this.querySelector('textarea[name="message"]').value;const telegramBotToken='7090576897:AAH3vxzJe8L4Cp0IOLfMF_Kr36EeWzhJsiM',chatId='1406491528',telegramApiUrl=`https://api.telegram.org/bot${telegramBotToken}/sendMessage`,text=`New message from contact form:\n\nName: ${name}\nEmail: ${email}\nSubject: ${subject}\nMessage: ${message}`;try{const response=await fetch(telegramApiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text})});if(response.ok){alert('Message sent successfully!');this.reset()}else throw new Error('Failed')}catch(error){console.error(error);alert('Failed to send message.')}});
const birthdayScript=document.createElement('script');birthdayScript.src='birthday-section.js?v=20260814-4';document.body.appendChild(birthdayScript);
const eggScript=document.createElement('script');eggScript.src='easter-eggs.js?v=20260814-4';document.body.appendChild(eggScript);