(function(){
 const MONTH=7,DAY=15,OFFSET=5*60*60*1000;
 function parts(){const d=new Date(Date.now()+OFFSET);return{year:d.getUTCFullYear(),month:d.getUTCMonth(),day:d.getUTCDate()}}
 function target(y){return Date.UTC(y,MONTH,DAY)-OFFSET}
 function birthday(p){return p.month===MONTH&&p.day===DAY}
 function year(p){if(p.month<MONTH||(p.month===MONTH&&p.day<DAY))return p.year;return p.year+1}
 function pad(v){return String(v).padStart(2,'0')}
 function tick(){const d=document.getElementById('birthdayDays'),h=document.getElementById('birthdayHours'),m=document.getElementById('birthdayMinutes'),s=document.getElementById('birthdaySeconds'),title=document.getElementById('birthdayCountdownTitle'),sub=document.getElementById('birthdayCountdownSubtitle'),cele=document.getElementById('birthdayCelebration'),status=document.getElementById('birthdayStatusText');if(!d||!h||!m||!s)return;const p=parts();if(birthday(p)){d.textContent=h.textContent=m.textContent=s.textContent='00';title.textContent='Сегодня день рождения! 🎉';sub.textContent='Birthday System активирован на весь день по времени Ташкента.';status.textContent='LEVEL UP • Birthday mode online';cele?.classList.add('show');return}cele?.classList.remove('show');const y=year(p),diff=Math.max(0,target(y)-Date.now()),t=Math.floor(diff/1000);d.textContent=Math.floor(t/86400);h.textContent=pad(Math.floor(t%86400/3600));m.textContent=pad(Math.floor(t%3600/60));s.textContent=pad(t%60);title.textContent='До следующего дня рождения';sub.textContent=`15 августа ${y} • 00:00 • Ташкент`;status.textContent=`Следующий LEVEL UP: 15.08.${y}`}
 function init(){tick();setInterval(tick,1000);const cake=document.getElementById('birthdayEmblem');if(cake){cake.style.cursor='pointer';cake.style.userSelect='none';cake.style.webkitUserSelect='none';let n=0,reset;cake.addEventListener('click',()=>{n++;clearTimeout(reset);reset=setTimeout(()=>n=0,2500);if(n>=3){n=0;location.href='birthday/?v=20260814-6'}})}}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();