(()=>{const css=document.createElement('link');css.rel='stylesheet';css.href='styles/easter-eggs.css?v=20260814-6';document.head.appendChild(css);const toast=document.createElement('div');toast.className='egg-toast';document.body.appendChild(toast);let timer;function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2400)}function clicks(el,count,fn){if(!el)return;el.style.userSelect='none';el.style.webkitUserSelect='none';let n=0,reset;el.addEventListener('click',()=>{n++;clearTimeout(reset);reset=setTimeout(()=>n=0,3000);if(n>=count){n=0;fn()}})}
clicks(document.querySelector('#home .image'),7,()=>{document.body.classList.add('egg-rainbow');say('🌈 HOME EGG: RGB MODE UNLOCKED');setTimeout(()=>document.body.classList.remove('egg-rainbow'),5000)});
clicks(document.querySelector('#about .main-title'),5,()=>{say('🧠 ABOUT EGG: curiosity.exe is running');document.querySelector('#about')?.classList.add('egg-flash');setTimeout(()=>document.querySelector('#about')?.classList.remove('egg-flash'),900)});
clicks(document.querySelector('#portfolio .main-title'),8,()=>{say('💻 PORTFOLIO EGG: BUILD MODE');const b=document.createElement('div');b.className='egg-secret-badge';b.textContent='BUILD • FOUND';document.body.appendChild(b);setTimeout(()=>b.remove(),6000)});
clicks(document.querySelector('#contact .main-title'),6,()=>{say('📡 CONTACT EGG: SIGNAL FOUND');document.body.classList.add('egg-matrix');setTimeout(()=>document.body.classList.remove('egg-matrix'),1700)});
let me=null;document.querySelectorAll('#contact .main-title span').forEach(s=>{if(s.textContent.trim().toLowerCase()==='me')me=s});if(!me){const title=document.querySelector('#contact .main-title');if(title){const walker=document.createTreeWalker(title,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode;if(/\bme\b/i.test(node.nodeValue)){const wrapper=document.createElement('span');wrapper.className='dev-me-trigger';wrapper.textContent=node.nodeValue.match(/\bme\b/i)[0];const before=node.nodeValue.slice(0,node.nodeValue.search(/\bme\b/i)),after=node.nodeValue.slice(node.nodeValue.search(/\bme\b/i)+wrapper.textContent.length);node.parentNode.insertBefore(document.createTextNode(before),node);node.parentNode.insertBefore(wrapper,node);node.nodeValue=after;me=wrapper;break}}}}
clicks(me,5,()=>{localStorage.setItem('portfolio-dev-mode','1');document.body.classList.add('portfolio-dev-mode');say('⚡ DEVELOPER MODE ENABLED');if(!document.querySelector('.dev-mode-indicator')){const d=document.createElement('div');d.className='egg-secret-badge dev-mode-indicator';d.textContent='DEV MODE • ON';document.body.appendChild(d)}});
if(localStorage.getItem('portfolio-dev-mode')==='1'){document.body.classList.add('portfolio-dev-mode');const d=document.createElement('div');d.className='egg-secret-badge dev-mode-indicator';d.textContent='DEV MODE • ON';document.body.appendChild(d)}
let keys='';addEventListener('keydown',e=>{keys=(keys+e.key.toLowerCase()).slice(-5);if(keys==='alios'){say('⚡ SECRET COMMAND: ALIOS ACCEPTED');document.querySelector('[data-id="birthday"]')?.classList.add('egg-flash')}});
})();