(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='styles/easter-eggs.css?v=20260814-8';document.head.appendChild(css);
 const toast=document.createElement('div');toast.className='egg-toast';document.body.appendChild(toast);
 let timer;
 function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),3000)}
 function clicks(el,count,fn){if(!el)return;el.classList.add('egg-trigger');let n=0,reset;el.addEventListener('click',()=>{n++;clearTimeout(reset);reset=setTimeout(()=>n=0,3000);if(n>=count){n=0;fn()}})}
 function closeArcade(){document.querySelector('.egg-arcade')?.remove()}
 function arcade(title,body){closeArcade();const box=document.createElement('div');box.className='egg-arcade';box.innerHTML=`<div class="egg-arcade-head"><button class="egg-back">← Назад</button><b>${title}</b><span>SECRET MODULE</span></div><div class="egg-arcade-body">${body}</div>`;document.body.appendChild(box);box.querySelector('.egg-back').onclick=closeArcade;return box}
 function planeGame(){say('🥚 ПАСХАЛКА НАЙДЕНА • SKY RUNNER ✈️');const box=arcade('SKY RUNNER',`<div class="sky-score">SCORE <b>0</b></div><div class="sky-game" tabindex="0"><div class="sky-plane">✈️</div><div class="sky-cloud">☁️</div><div class="sky-help">Тапай по полю или нажимай SPACE</div></div>`);const game=box.querySelector('.sky-game'),plane=box.querySelector('.sky-plane'),cloud=box.querySelector('.sky-cloud'),scoreEl=box.querySelector('.sky-score b');let y=50,v=0,score=0,alive=true;const jump=()=>{if(alive)v=-7};game.onclick=jump;addEventListener('keydown',function key(e){if(e.code==='Space'&&document.body.contains(box)){e.preventDefault();jump()}if(!document.body.contains(box))removeEventListener('keydown',key)});let x=105;function frame(){if(!document.body.contains(box)||!alive)return;v+=.38;y+=v;x-=1.15;if(x<-15){x=110;score++;scoreEl.textContent=score}y=Math.max(4,Math.min(86,y));plane.style.top=y+'%';cloud.style.left=x+'%';if(x>4&&x<22&&y>32&&y<68){alive=false;box.querySelector('.sky-help').textContent='GAME OVER • score '+score+' • ← Назад'}else requestAnimationFrame(frame)}requestAnimationFrame(frame)}
 function memoryGame(){say('🥚 ПАСХАЛКА НАЙДЕНА • MEMORY GRID 🧠');const icons=['⚡','🎂','💻','🚀','⚡','🎂','💻','🚀'].sort(()=>Math.random()-.5);const box=arcade('MEMORY GRID',`<p class="arcade-note">Найди 4 пары.</p><div class="memory-grid">${icons.map((x,i)=>`<button data-v="${x}" data-i="${i}">?</button>`).join('')}</div>`);let open=[],done=0;box.querySelectorAll('.memory-grid button').forEach(b=>b.onclick=()=>{if(b.disabled||open.length===2)return;b.textContent=b.dataset.v;open.push(b);if(open.length===2){if(open[0].dataset.v===open[1].dataset.v){open.forEach(x=>x.disabled=true);open=[];done++;if(done===4)say('🏆 MEMORY GRID COMPLETE')}else setTimeout(()=>{open.forEach(x=>x.textContent='?');open=[]},650)}})}
 function reactor(){say('🥚 ПАСХАЛКА НАЙДЕНА • REACTOR ⚡');const box=arcade('REACTOR',`<div class="reactor"><div class="reactor-core">⚡</div><h2>0%</h2><p>Нажимай на ядро и заряди его до 100%.</p></div>`);let p=0;box.querySelector('.reactor-core').onclick=()=>{p=Math.min(100,p+10);box.querySelector('.reactor h2').textContent=p+'%';box.querySelector('.reactor').style.setProperty('--power',p+'%');if(p===100){say('⚡ REACTOR ONLINE');box.querySelector('.reactor p').textContent='SYSTEM ONLINE • 100%'}}}
 function signal(){say('🥚 ПАСХАЛКА НАЙДЕНА • SIGNAL 📡');const box=arcade('SIGNAL',`<div class="signal-game"><div class="signal-ring">📡</div><h2>Найди сигнал</h2><p>Нажми на антенну 5 раз.</p><b>0 / 5</b></div>`);let n=0;box.querySelector('.signal-ring').onclick=()=>{n++;box.querySelector('.signal-game b').textContent=Math.min(n,5)+' / 5';if(n>=5){say('📡 SIGNAL LOCKED');box.querySelector('.signal-game h2').textContent='CONNECTED'}}}
 clicks(document.querySelector('#home .left-header .image'),2,()=>{say('🥚 ПАСХАЛКА НАЙДЕНА • PHOTO PORTAL');reactor()});
 clicks(document.querySelector('#home .name'),7,()=>{document.body.classList.add('egg-rainbow');say('🥚 ПАСХАЛКА НАЙДЕНА • RGB MODE 🌈');setTimeout(()=>document.body.classList.remove('egg-rainbow'),5000);planeGame()});
 clicks(document.querySelector('#about .main-title'),5,memoryGame);
 clicks(document.querySelector('#portfolio .main-title'),8,reactor);
 clicks(document.querySelector('#contact .main-title'),6,signal);
 let me=null;document.querySelectorAll('#contact .main-title span').forEach(s=>{if(s.textContent.trim().toLowerCase()==='me')me=s});
 clicks(me,5,()=>{localStorage.setItem('portfolio-dev-mode','1');document.body.classList.add('portfolio-dev-mode');say('🥚 ПАСХАЛКА НАЙДЕНА • DEVELOPER MODE ⚡');if(!document.querySelector('.dev-mode-indicator')){const d=document.createElement('div');d.className='egg-secret-badge dev-mode-indicator';d.textContent='DEV MODE • ON';document.body.appendChild(d)}});
 if(localStorage.getItem('portfolio-dev-mode')==='1'){document.body.classList.add('portfolio-dev-mode');if(!document.querySelector('.dev-mode-indicator')){const d=document.createElement('div');d.className='egg-secret-badge dev-mode-indicator';d.textContent='DEV MODE • ON';document.body.appendChild(d)}}
 let keys='';addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;keys=(keys+e.key.toLowerCase()).slice(-5);if(keys==='alios'){say('🥚 PC SECRET FOUND • ALIOS TERMINAL');planeGame();keys=''}});
 window.AliEggs={say,arcade,planeGame,memoryGame,reactor,signal};
})();