const birthdayTime=new Date('2026-08-15T00:00:00+05:00').getTime();
const startWindow=new Date('2026-08-14T00:00:00+05:00').getTime();
const locked=document.getElementById('lockedScreen'),birthday=document.getElementById('birthdayScreen');
const h=document.getElementById('hours'),m=document.getElementById('minutes'),s=document.getElementById('seconds'),progress=document.getElementById('progressBar'),lockStatus=document.getElementById('lockStatus');
let started=false,confettiRunning=false,ageClicks=0;
function pad(n){return String(n).padStart(2,'0')}
function tick(){const now=Date.now(),diff=birthdayTime-now;if(diff<=0){openBirthday();return}const total=Math.floor(diff/1000);h.textContent=pad(Math.floor(total/3600));m.textContent=pad(Math.floor(total%3600/60));s.textContent=pad(total%60);const pct=Math.max(0,Math.min(100,((now-startWindow)/(birthdayTime-startWindow))*100));progress.style.width=pct+'%';lockStatus.textContent=diff<3600000?'Финальная проверка... осталось меньше часа.':'Сюрприз зашифрован. Доступ пока закрыт.'}
function openBirthday(){if(started)return;started=true;locked.classList.add('hidden');birthday.classList.remove('hidden');typeTerminal();launchConfetti(220);}
setInterval(tick,250);tick();
const terminal=document.getElementById('terminalText');
const lines=['> boot birthday-system --version 14.0','> user: Muhammadali','> birth_date: 15.08.2012','> loading modules...','> creativity ........ OK','> programming ....... OK','> big_projects ...... OK','> curiosity ......... OK','','> LEVEL 14 SUCCESSFULLY UNLOCKED 🎂'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function typeTerminal(){terminal.textContent='';for(const line of lines){for(const ch of line){terminal.textContent+=ch;await sleep(18)}terminal.textContent+='\n';await sleep(120)}}
document.getElementById('surpriseButton').onclick=()=>{document.getElementById('secret').classList.remove('hidden');launchConfetti(300);document.getElementById('secret').scrollIntoView({behavior:'smooth',block:'center'})};
document.getElementById('missionButton').onclick=()=>{document.getElementById('missionPanel').classList.toggle('hidden');document.getElementById('missionPanel').scrollIntoView({behavior:'smooth',block:'center'})};
document.getElementById('ageButton').onclick=()=>{ageClicks++;if(ageClicks===1)document.querySelector('.hint').textContent='Хм... кажется, нужно ещё несколько раз 👀';if(ageClicks>=5){document.getElementById('easterEgg').classList.remove('hidden');launchConfetti(500);ageClicks=0}};
document.getElementById('closeEgg').onclick=()=>document.getElementById('easterEgg').classList.add('hidden');
const bg=document.getElementById('backgroundCanvas'),bgx=bg.getContext('2d');let stars=[];function resizeBg(){bg.width=innerWidth;bg.height=innerHeight;stars=Array.from({length:Math.min(120,Math.floor(innerWidth/8))},()=>({x:Math.random()*bg.width,y:Math.random()*bg.height,r:Math.random()*1.5+.2,a:Math.random()}))}function drawBg(){bgx.clearRect(0,0,bg.width,bg.height);const g=bgx.createRadialGradient(bg.width*.5,bg.height*.25,0,bg.width*.5,bg.height*.25,Math.max(bg.width,bg.height)*.75);g.addColorStop(0,'#111d50');g.addColorStop(.45,'#060914');g.addColorStop(1,'#020307');bgx.fillStyle=g;bgx.fillRect(0,0,bg.width,bg.height);for(const st of stars){st.a+=.01;bgx.globalAlpha=.25+Math.abs(Math.sin(st.a))*.55;bgx.fillStyle='#b8c5ff';bgx.beginPath();bgx.arc(st.x,st.y,st.r,0,Math.PI*2);bgx.fill()}bgx.globalAlpha=1;requestAnimationFrame(drawBg)}addEventListener('resize',resizeBg);resizeBg();drawBg();
const canvas=document.getElementById('confetti'),ctx=canvas.getContext('2d');let pieces=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();function launchConfetti(count){for(let i=0;i<count;i++)pieces.push({x:Math.random()*canvas.width,y:-20-Math.random()*canvas.height*.7,w:4+Math.random()*7,h:6+Math.random()*10,vy:2+Math.random()*4,vx:-1.5+Math.random()*3,r:Math.random()*6.28,vr:-.1+Math.random()*.2,hue:Math.random()*360,life:350+Math.random()*250});if(!confettiRunning){confettiRunning=true;animateConfetti()}}function animateConfetti(){ctx.clearRect(0,0,canvas.width,canvas.height);pieces=pieces.filter(p=>p.life-->0&&p.y<canvas.height+40);for(const p of pieces){p.x+=p.vx;p.y+=p.vy;p.r+=p.vr;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=`hsl(${p.hue} 90% 65%)`;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore()}if(pieces.length)requestAnimationFrame(animateConfetti);else confettiRunning=false}